version: '3.9'
services:
  backend:
    build: ./backend
    container_name: handyman-backend
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELNYX_API_KEY: ${TELNYX_API_KEY}
      TELNYX_FROM: ${TELNYX_FROM:-+19803167792}
      TELNYX_PROFILE_ID: ${TELNYX_PROFILE_ID}
      TELNYX_WEBHOOK_URL: ${TELNYX_WEBHOOK_URL}
      TELNYX_WEBHOOK_FAILOVER_URL: ${TELNYX_WEBHOOK_FAILOVER_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_STORAGE_BUCKET: ${SUPABASE_STORAGE_BUCKET:-uploads}
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: handyman-frontend
    environment:
      - VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped


