version: '3.9'
services:
  backend:
    build: ./backend
    container_name: handyman-backend
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELNYX_API_KEY: ${TELNYX_API_KEY}
      TELNYX_FROM: ${TELNYX_FROM:-+19803167792}
      TELNYX_PROFILE_ID: ${TELNYX_PROFILE_ID}
      TELNYX_WEBHOOK_URL: ${TELNYX_WEBHOOK_URL}
      TELNYX_WEBHOOK_FAILOVER_URL: ${TELNYX_WEBHOOK_FAILOVER_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_STORAGE_BUCKET: ${SUPABASE_STORAGE_BUCKET:-uploads}
    ports:
      - "8080:8080"
    restart: unless-stopped


